### ISSUE TITLE
igo crashed

### ISSUE THREAD

**Issue by sindhus** [takluyver/igo#3]
Hi!

I installed igo using `go get` and when I ran it I get:

```
➜  ~  ipython console --KernelManager.kernel_cmd="['igo', '{connection_file}']"
Traceback (most recent call last):
  File "//Users/sindhus/Library/Python/2.7/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/config/application.py", line 563, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/core/application.py", line 381, in initialize
    self.parse_command_line(argv)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/config/application.py", line 475, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/config/application.py", line 413, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/config/application.py", line 92, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/terminal/ipapp.py", line 332, in initialize
    self.init_shell()
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/terminal/console/app.py", line 107, in init_shell
    IPythonConsoleApp.initialize(self)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/consoleapp.py", line 385, in initialize
    self.init_kernel_manager()
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/consoleapp.py", line 341, in init_kernel_manager
    self.kernel_manager.start_kernel(extra_arguments=self.kernel_argv)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/kernel/manager.py", line 217, in start_kernel
    **kw)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/kernel/manager.py", line 173, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/sindhus/Library/Python/2.7/lib/python/site-packages/IPython/kernel/launcher.py", line 260, in launch_kernel
    stdin=_stdin, stdout=_stdout, stderr=_stderr, cwd=cwd, env=os.environ)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

**Comment by takluyver** [comment]
There is now a new Go kernel called [gophernotes](https://github.com/gophergala2016/gophernotes) that appears to be much more capable than igo. I'd recommend using that.

**Comment by sindhus** [comment]
thanks!
